Repository umijs/umi-next, pull requests merged in 2020-01, with the labels that each got.

#19 feat: dev proxy middleware
  docs/packages/server.md
  packages/preset-built-in/src/index.test.ts
  packages/preset-built-in/src/plugins/commands/dev/dev.ts
  packages/server/package.json
  packages/server/src/Server/Server.test.ts
  packages/server/src/Server/Server.ts
Labels: enhancement

#20 chore(core): use lodash.get
  packages/core/src/Config/Config.ts
  packages/core/src/Config/utils/configUtils.ts
Labels: pr(chore)

#21 fix: server proxy middleware
  packages/server/src/Server/Server.test.ts
  packages/server/src/Server/Server.ts
Labels: bug

#22 feat: mock middleware
  .github/workflows/ci.yml
  azure-pipelines.yml
  packages/core/src/Service/Service.ts
  packages/preset-built-in/package.json
  packages/preset-built-in/src/index.ts
  packages/preset-built-in/src/plugins/commands/dev/dev.ts
  packages/preset-built-in/src/plugins/commands/dev/mock/createMiddleware.test.ts
  packages/preset-built-in/src/plugins/commands/dev/mock/createMiddleware.ts
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/createMiddleware/mock/a.js
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/createMiddleware/pages/.gitkeep
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/mock-files/.umirc.js
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/mock-files/mock/a.js
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/mock-files/mock/a_2.js
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/mock-files/mock/b.js
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/mock-files/mock/string.js
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/mock-files/mock/with-keys.js
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/mock-files/mock/with-method.js
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/normal/mock/_c.js
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/normal/mock/a.js
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/normal/mock/b.js
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/normal/pages/a/_mock.js
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/normal/pages/b/_mock.js
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/parse-failed/mock/error.js
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/ts/mock/a.ts
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/umirc-mock-file/.umirc.mock.js
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/umirc-mock-file/mock/a.js
  packages/preset-built-in/src/plugins/commands/dev/mock/mock.ts
  packages/preset-built-in/src/plugins/commands/dev/mock/utils.test.ts
  packages/preset-built-in/src/plugins/commands/dev/mock/utils.ts
  packages/preset-built-in/src/plugins/registerMethods.ts
  packages/server/src/Server/Server.ts
  packages/types/index.d.ts
  packages/utils/package.json
  packages/utils/src/index.ts
  yarn.lock
Labels: enhancement
