Repository umijs/umi-next, pull requests merged in 2022-04, with the labels that each got.

#575 feat(plugin-docs): Add Markdown table syntax support
  packages/plugin-docs/client/theme-doc/tailwind.css
  packages/plugin-docs/compiled/remark-gfm/LICENSE
  packages/plugin-docs/compiled/remark-gfm/index.cjs
  packages/plugin-docs/compiled/remark-gfm/package.json
  packages/plugin-docs/src/compiler.ts
Labels: enhancement

#614 📝 Docs/styling
  docs/docs/guides/styling.md
Labels: documentation

#615 📝 Docs/typescript
  docs/docs/guides/typescript.md
Labels: documentation

#611 📝 Doc/testing
  docs/docs/guides/test.md
  examples/test-test/.umirc.ts
  examples/test-test/components/Greet/Greet.test.tsx
  examples/test-test/components/Greet/Greet.tsx
  examples/test-test/components/Greet/__snapshots__/Greet.test.tsx.snap
  examples/test-test/components/Greet/index.ts
  examples/test-test/jest.config.ts
  examples/test-test/package.json
  examples/test-test/utils/reverseApiData.test.ts
  examples/test-test/utils/reverseApiData.ts
  packages/preset-umi/src/commands/generators/jest.ts
  packages/preset-umi/src/commands/generators/utils.ts
  pnpm-lock.yaml
Labels: documentation

#624 docs: add lint guide
  docs/docs/guides/lint.md
Labels: documentation

#623 docs: 📝 layout-memu 文档
  docs/docs/max/layout-menu.md
Labels: documentation

#643 feat(plugin-docs): Add configs for customize head of plugin-docs
  packages/plugin-docs/client/theme-doc/Head.tsx
  packages/plugin-docs/client/theme-doc/Logo.tsx
  packages/plugin-docs/client/theme-doc/context.ts
Labels: documentation, enhancement

#634 feat(plugin-docs): Add theme config for hide the theme switch
  packages/plugin-docs/client/theme-doc/Head.tsx
  packages/plugin-docs/client/theme-doc/ThemeSwitch.tsx
  packages/plugin-docs/client/theme-doc/context.ts
  theme.config.ts
Labels: enhancement

#653 fix(plugin-docs): Fix #644 TOC link makes page reload loop
  packages/plugin-docs/src/compiler.ts
Labels: bug, documentation

#654 fix(plugin-docs): Fix #645 mdx error if there is brackets in docs
  docs/docs/api/runtime-config.md
  packages/plugin-docs/client/theme-doc/Toc.tsx
Labels: bug, documentation

#657 feat(plugin-docs): Add dropdown for nav items
  packages/plugin-docs/client/theme-doc/NavBar.tsx
  packages/plugin-docs/client/theme-doc/context.ts
Labels: documentation, enhancement

#658 fix(plugin-docs): Fix bug that not scroll to top when route change
  packages/plugin-docs/src/compiler.ts
Labels: bug, documentation

#674 feat(plugin-docs): Add id attribute of search input component for style override
  packages/plugin-docs/client/theme-doc/Search.tsx
Labels: documentation, enhancement

#684 feat(plugin-docs): Add id attribute of page container and header title
  packages/plugin-docs/client/theme-doc/Layout.tsx
  packages/plugin-docs/client/theme-doc/Logo.tsx
Labels: documentation, enhancement

#699 fix(plugin-docs): Fix plugin search cannot find level 3 title bug
  packages/plugin-docs/client/theme-doc/Search.tsx
  packages/plugin-docs/client/theme-doc/Toc.tsx
  packages/plugin-docs/client/theme-doc/utils/getLinkFromTitle.ts
Labels: bug, documentation

#701 fix(plugin-docs): Fix home page horizontal scroll bar bug
  packages/plugin-docs/client/theme-doc/components/Features.tsx
Labels: bug

#706 feat(plugin-docs): scroll side nav to selected position
  packages/plugin-docs/client/theme-doc/Sidebar.tsx
  packages/plugin-docs/src/compiler.ts
Labels: documentation, enhancement

#722 fix(plugin-docs): Fix firefox glossy background polyfill bug and add default locale
  packages/plugin-docs/client/theme-doc/LangSwitch.tsx
  packages/plugin-docs/client/theme-doc/Layout.tsx
  packages/plugin-docs/client/theme-doc/Search.tsx
  packages/plugin-docs/client/theme-doc/components/Announcement.tsx
  packages/plugin-docs/client/theme-doc/firefox-polyfill.css
  packages/plugin-docs/client/theme-doc/useLanguage.ts
Labels: documentation
